import type { Metadata } from "next";
import { Header } from "./_components/Header";
import "./globals.css";
import "@/assets/fonts/index.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="text-[16px] max-md:text-[14px]" lang="en">
      <body className="w-full max-w-[50rem] h-full m-auto">
        <Header />

        {children}
      </body>
    </html>
  );
}
