# [v]: 사용되지 않는 cd 스크립트 주석 처리

#name: Auto Deployment
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  deploy_master:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set up Environment
#        run: echo "${{ secrets.PROD_ENV_PROPERTIES }}" > ./.env
#
#      - name: Send env file
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{secrets.RELEASE_HOST}}
#          username: ${{ secrets.RELEASE_USERNAME}}
#          password: ${{ secrets.RELEASE_PASSWORD}}
#          source: "./.env"
#          target: "~/git-repo/junghyunbak"
#
#      - name: ssh action
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.RELEASE_HOST }}
#          username: ${{ secrets.RELEASE_USERNAME }}
#          password: ${{ secrets.RELEASE_PASSWORD }}
#          script: |
#            cd ./git-repo/junghyunbak
#
#            git clean -fd
#            git checkout master
#            git pull origin master
#
#            ./docker/build-and-run.sh
